apiVersion: v1
kind: PersistentVolume
metadata:
  name: cometaiac-pv
spec:
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteOnce
  azureDisk:
    kind: Managed
    diskName: cometaiac_dsk
    diskURI: /subscriptions/02b9c0e0-8708-46b2-90f1-c26c6f065acc/resourcegroups/tfm_rg/providers/Microsoft.Compute/disks/cometaiac_dsk