name: Build, Push and Aks Deploy

on:
  push:
    branches:
      - main

jobs:
  compile_python_code:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Compile Python code
        run: python -m compileall .

  unit_tests:
    needs: compile_python_code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run unit tests
        run: pytest

  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build Docker Node Image
      uses: docker/build-push-action@v5.0.0
      with:
        file: ./dockerfile
        push: false
        tags: ${{ secrets.ACR_SERVER }}/cometaiac:latest

  push:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Docker Login
      uses: docker/login-action@v3.0.0
      with:
        registry: ${{ secrets.ACR_SERVER }}
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASS }}
        logout: true

    - name: Push Docker Image
      uses: docker/build-push-action@v5.0.0
      with:
        file: ./dockerfile
        push: true
        tags: ${{ secrets.ACR_SERVER }}/cometaiac:latest

  deploy_aks:
    needs: push
    runs-on: ubuntu-latest
    steps:
    - name: Azure login
      uses: azure/login@v1.4.3
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Set AKS context
      uses: azure/aks-set-context@v3
      with:
        resource-group: ${{ secrets.AKS_RG }}
        cluster-name: ${{ secrets.AKS_NAME }}

    - name: Setup kubectl
      uses: azure/setup-kubectl@v3

    - name: Deploy Persistence to AKS
      uses: Azure/k8s-deploy@v4
      with:
        namespace: ${{ secrets.AKS_NAMESPACE }}
        manifests: k8s/persistence

    - name: Deploy Node to AKS
      uses: Azure/k8s-deploy@v4
      with:
        namespace: ${{ secrets.AKS_NAMESPACE }}
        manifests: k8s/cometaiac
