name: Compile, Analysis, Build, Push and Aks Deploy

on:
  push:
    branches:
      - main

jobs:
  compile_python_code:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.1

      - name: Set up Python
        uses: actions/setup-python@v5.0.0
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Compile Python code
        run: python -m compileall .

  sonar_analysis:
    needs: compile_python_code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.1

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v2.1.1
        env:
           GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
           SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.organization=jsmuown
            -Dsonar.projectKey=cometaIAC

  build:
    needs: sonar_analysis
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4.1.1

    - name: Build Docker Node Image
      uses: docker/build-push-action@v5.0.0
      with:
        file: ./Dockerfile
        push: false
        tags: ${{ secrets.ACR_SERVER }}/cometaiac:latest

  push:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Docker Login
      uses: docker/login-action@v3.0.0
      with:
        registry: ${{ secrets.ACR_SERVER }}
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASS }}
        logout: true

    - name: Push Docker Image
      uses: docker/build-push-action@v5.0.0
      with:
        file: ./Dockerfile
        push: true
        tags: ${{ secrets.ACR_SERVER }}/cometaiac:latest

  deploy_aks:
    needs: push
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4.1.1

    - name: Azure login
      uses: azure/login@v1.4.3
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Set AKS context
      uses: azure/aks-set-context@v3
      with:
        resource-group: ${{ secrets.AKS_RG }}
        cluster-name: ${{ secrets.AKS_NAME }}

    - name: Setup kubectl
      uses: azure/setup-kubectl@v3

    - name: Deploy Persistence to AKS
      uses: Azure/k8s-deploy@v4
      with:
        namespace: ${{ secrets.AKS_NAMESPACE }}
        manifests: k8s/persistence

    - name: Deploy CometaIAC to AKS
      uses: Azure/k8s-deploy@v4
      with:
        namespace: ${{ secrets.AKS_NAMESPACE }}
        manifests: k8s/cometaiac
